### PR TITLE
possible fix for IE weirdness

### PR DESCRIPTION
**Pull request by calvinmetcalf**
fixes #51 and #56

### CODE REVIEW

**Comment by defunctzombie** [comment]
Any way to get a test for this?

**Comment by calvinmetcalf** [comment]
not without more info for how it's actually breaking in IE

**Comment by defunctzombie** [comment]
LGTM, feel free to merge.

I also added you as a collaborator on the project. Feel free to tackle anything without waiting on me if I am blocking. I think you know the main goals here: avoid bloat, and be careful. We don't need to get too creative here as this stuff has been pretty battle tested by now I think and we can focus on incremental fixes.

**Comment by calvinmetcalf** [comment]
thanks!

**Comment by chrisradek** [comment]
We recently ran into this issue as well. Do you mind publishing a new release to npm?

Thanks!

**Comment by defunctzombie** [comment]
@calvinmetcalf do you know the process to publish?

**Comment by calvinmetcalf** [comment]
i assume it's npm version followed by npm publish

**Comment by defunctzombie** [comment]
Yep. 👍 What is your npm username?

**Comment by calvinmetcalf** [comment]
cwmma

**Comment by defunctzombie** [comment]
@calvinmetcalf added as owner. You should be able to publish as needed now.

**Comment by calvinmetcalf** [comment]
done

**Comment by chrisradek** [comment]
@calvinmetcalf @defunctzombie 
Thanks for the quick turn-around!

**Comment by calvinmetcalf** [comment]
@chrisradek any change you could help the edge team reproduce https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7206104/

**Pull request merged**
